---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: spc-deploy
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: spc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: spc-pod
      labels:
        app: spc
      annotations:
        CHANGE-CAUSE: for rollout testing
    spec:
      containers:
        - name: spc-ctnr
          image: srikanthvelma/spc:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            exec:
              command:
              - echo
              - this is livenessProbe
            initialDelaySeconds: 5
            periodSeconds: 5
            # httpGet:
            #   path: /
            #   port: 80
            # initialDelaySeconds: 3
            # periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata: 
  name: spc-svc
spec:
  type: LoadBalancer
  selector:
    app: spc
  ports:
    - name: spc-port 
      port: 8080
      targetPort: 8080
      protocol: TCP

